TARGET = LinuxEssentialsHandbook.pdf
TARGET += epam-Linux_courses_handbook.pdf

.PHONY: all tex clean

all: tex

tex: $(TARGET)

%.pdf: %.tex
	pdflatex -interaction=nonstopmode $<
	pdflatex -interaction=nonstopmode $<
	pdflatex -interaction=nonstopmode $<

clean: 
	@rm -f *.aux
	@rm -f *.vrb
	@rm -f *.snm
	@rm -f *.log
	@rm -f *.out
	@rm -f *.toc
	@rm -f *.nav
	@rm -f $(TARGET)
