PROGRAM_NAME=hello100
CPPFLAGS=--coverage
#CPPFLAGS=-ftest-coverage -fprofile-arcs

all:
	gcc $(CPPFLAGS) -o $(PROGRAM_NAME) hello100.c

clean:
	rm -f $(PROGRAM_NAME) *.gcno *.gcda *.gcov *.html *.htm


